### ISSUE TITLE
Странная ссылка

### ISSUE THREAD

**Issue by Morfey216** [MrRobot-p/Meine-coon#2]
Поясни назначение ссылки в этой строке:
https://github.com/MrRobot-p/Meine-coon/blob/3ef71e1e2f18dfd2061440312c2174a25e717a9c/src/index.html#L196

**Comment by MrRobot-p** [comment]
Видимо сделал ошибку, следовало использовать обычный button, либо span

пн, 11 окт. 2021 г. в 16:32, Сергей Стреха ***@***.***>:
