### ISSUE TITLE
Файл button.scss

### ISSUE THREAD

**Issue by Morfey216** [MrRobot-p/Meine-coon#4]
1. высоту кнопки обычно определяют через паддинги, а не  `min-height` https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/button/button.scss#L4
2. Условия в медиа-выражениях указаны неверно https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/button/button.scss#L67
3. `min-width: 320px` можно не указывать, это условие избыточно
4. Избыточное медиа-выражение https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/button/button.scss#L53 Действует принцип водопада: стили работают до момента переопределения. Настройки прозрачности можно вынести за пределы условия.
5. Дублирование стилей: https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/button/button.scss#L69-L70 https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/button/button.scss#L85-L86 от одного из выражений можно отказаться
6. Свойства рекомендуется группировать по принадлежности к своим группам.
Например: 
```
.header__btn {
  display: block;
  width: 200px;
  margin-bottom: 110px;
  padding: 18px;
  overflow: hidden;

  font-weight: bold;
  font-size: 14px;
  line-height: 14px;
  font-family: "Roboto", "Arial", sans-serif;
  text-align: center;
  color: #ffffff;
  text-decoration: none;
  font-style: normal;

  background-color: transparent;
  border: 1px solid #a07b50;
  cursor: pointer;

  transition: color 0.3s ease-out, border 0.3s ease-out;
}
```

Исправить по всему коду...

**Comment by MrRobot-p** [comment]
Сделано
