### ISSUE TITLE
Файл header.scss

### ISSUE THREAD

**Issue by Morfey216** [MrRobot-p/Meine-coon#6]
1. Надо объединять свойства внутри селектора, а не раскидывать поодиночке: https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/header/header.scss#L247 https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/header/header.scss#L270-L272 https://github.com/MrRobot-p/Meine-coon/blob/534eb7b2243742b29a9cb949b18d8a5fcb43a357/src/scss/components/header/header.scss#L278-L280
2. Бургер виден на планшетной версии http://joxi.ru/KAx48GoTvjjznA И нет меню...
3. На какой странице мы сейчас находимся? http://joxi.ru/DmBObWLsgYYVD2
Нужно прописать текущий пункт меню

**Comment by MrRobot-p** [comment]
Исправлено
